(()=>{
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const root=document.body;
// immersive layers
const canvas=document.createElement('canvas'); canvas.id='alanOSCanvas'; root.prepend(canvas);
['os-noise','os-scanlines'].forEach(c=>{const d=document.createElement('div');d.className=c;root.appendChild(d)});
const corners=document.createElement('div');corners.className='os-corners';corners.innerHTML='<i></i><i></i><i></i><i></i>';root.appendChild(corners);
const hud=document.createElement('div');hud.className='os-hud';hud.innerHTML='<div class="hud-row"><span>ALAN.OS</span><b>ONLINE</b></div><div class="hud-row"><span>MODE</span><b id="osMode">EXPLORATION</b></div><div class="hud-row"><span>LOCAL TIME</span><b id="osTime">--:--:--</b></div><div class="hud-row"><span>SCROLL</span><b id="osScroll">000%</b></div><div class="hud-row"><span>CORE LOAD</span><b id="osLoad">--%</b></div><div class="bar"><span id="osBar"></span></div>';root.appendChild(hud);
const dock=document.createElement('div');dock.className='os-dock';dock.innerHTML='<button data-os="map">DIGITAL TWIN</button><button data-os="console">ALAN.OS</button><button data-os="ai">ASK AEON</button><button data-os="top">TOP</button>';root.appendChild(dock);
const boot=document.createElement('div');boot.className='os-boot';boot.innerHTML='<div class="boot-box"><div class="boot-brand">ALAN.OS</div><div>PERSONAL SYSTEM // DIGITAL TWIN</div><div class="boot-line"></div><div class="boot-log"><div>> booting kernel ........ <b>OK</b></div><div>> loading intelligence ... <b>OK</b></div><div>> mapping robotics ...... <b>OK</b></div><div>> linking projects ...... <b>OK</b></div><div>> initializing field core <b>READY</b></div></div><div class="boot-progress"><span></span></div></div>';root.appendChild(boot);
setTimeout(()=>boot.classList.add('hide'),2300);
const consoleEl=document.createElement('div');consoleEl.className='os-console';consoleEl.innerHTML='<div class="os-window"><div class="os-titlebar"><span>ALAN.OS // COMMAND TERMINAL</span><button aria-label="close">×</button></div><div class="os-console-body"><div class="os-modules"><button class="active" data-view="system">SYSTEM</button><button data-view="aeon">AEON CORE</button><button data-view="robotics">ROBOTICS</button><button data-view="alpha">ALPHA LAB</button><button data-view="about">PROFILE</button></div><div class="os-terminal"><h3 id="osTitle">SYSTEM CORE</h3><div class="os-output" id="osOutput"></div><div class="os-ai-answer" id="osAnswer">Use o terminal para explorar o sistema.</div><div class="os-input"><span class="prompt">alan@os:~$</span><input id="osInput" placeholder="pergunte sobre AEON, robótica, skills..." autocomplete="off"></div></div></div></div>';root.appendChild(consoleEl);
const views={system:['SYSTEM CORE','ALAN.OS integra projetos, competências e direção profissional em uma interface única. O objetivo é demonstrar pensamento sistêmico: software + hardware + dados + automação + operação.'],aeon:['AEON CORE','Arquitetura experimental de agentes inteligentes, memória, RAG, conhecimento e orquestração. AEON é o laboratório cognitivo do ecossistema.'],robotics:['ROBOTICS STACK','Base construída com robótica educacional, eletrônica, prototipagem e automação. A direção futura conecta essas competências a sistemas remotos.'],alpha:['ALPHA LAB','Laboratório de modelos, dados, calibração, backtesting e experimentação. Um ambiente para transformar dados em hipóteses testáveis.'],about:['PROFILE','Bacharel em Sistemas de Informação com experiência prática em software, hardware, Linux, redes, dados, automação, robótica e diagnóstico de sistemas.']};
function showView(k){const v=views[k]||views.system;$('#osTitle',consoleEl).textContent=v[0];$('#osOutput',consoleEl).textContent=v[1]+'\n\nSTATUS: ONLINE\nMODE: RESEARCH / BUILD / LEARN';$$('.os-modules button',consoleEl).forEach(b=>b.classList.toggle('active',b.dataset.view===k))}
showView('system');
function openConsole(k='system'){consoleEl.classList.add('open');showView(k);setTimeout(()=>$('#osInput',consoleEl).focus(),50)}
function closeConsole(){consoleEl.classList.remove('open')}
$('.os-titlebar button',consoleEl).onclick=closeConsole;
$$('.os-modules button',consoleEl).forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#osInput',consoleEl).addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=e.target.value.trim().toLowerCase();let a='Não encontrei esse módulo. Tente: AEON, robótica, ALPHA, Linux, skills ou perfil.';if(q.includes('aeon'))a='AEON: núcleo experimental de inteligência. Trabalha com agentes, memória, RAG, conhecimento e orquestração.';else if(q.includes('rob'))a='Robótica: experiência educacional, eletrônica, prototipagem e automação. A aplicação a sistemas remotos é uma direção de pesquisa, não uma alegação de experiência operacional em ROV.';else if(q.includes('alpha')||q.includes('dado'))a='ALPHA: laboratório de modelos, backtesting, calibração e experimentação orientada por dados.';else if(q.includes('linux'))a='Linux: competência de infraestrutura e terminal, relevante para ambientes de desenvolvimento, automação e sistemas embarcados.';else if(q.includes('skill')||q.includes('compet'))a='Stack: IA/agentes, hardware, SQL/dados, JavaScript, C#, Linux, robótica, automação, redes, Fusion 360 e Navtor.';else if(q.includes('perfil')||q.includes('alan'))a='Alan Miranda: Sistemas de Informação + experiência prática multidisciplinar em tecnologia e operação.';$('#osAnswer',consoleEl).textContent=a;e.target.value='';});
$$('.os-dock button').forEach(b=>b.onclick=()=>{const a=b.dataset.os;if(a==='console'||a==='ai')openConsole(a==='ai'?'aeon':'system');else if(a==='top')scrollTo({top:0,behavior:'smooth'});else{const el=$('#alan-os-map');if(el)el.scrollIntoView({behavior:'smooth'})}});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openConsole()} if(e.key==='Escape')closeConsole()});
// telemetry
let t0=performance.now();function tick(){const d=new Date();$('#osTime').textContent=d.toLocaleTimeString('pt-BR');const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?Math.round(scrollY/max*100):0;$('#osScroll').textContent=String(pct).padStart(3,'0')+'%';const load=Math.round(35+Math.abs(Math.sin(Date.now()/1800))*55);$('#osLoad').textContent=load+'%';$('#osBar').style.width=load+'%';requestAnimationFrame(()=>setTimeout(tick,400))}tick();
// neural field
const ctx=canvas.getContext('2d');let W,H,dpr,nodes=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);nodes=Array.from({length:Math.min(90,Math.max(35,Math.floor(W/16)))},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:Math.random()*1.5+.5}))}resize();addEventListener('resize',resize);let mx=W/2,my=H/2;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY});function draw(){ctx.clearRect(0,0,W,H);for(const n of nodes){n.x+=n.vx;n.y+=n.vy;if(n.x<0||n.x>W)n.vx*=-1;if(n.y<0||n.y>H)n.vy*=-1;const dx=n.x-mx,dy=n.y-my,dist=Math.hypot(dx,dy);if(dist<150){n.x-=dx/dist*.15;n.y-=dy/dist*.15}}for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=i+1;j<nodes.length;j++){const b=nodes[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<115){ctx.strokeStyle=`rgba(94,234,212,${(1-d/115)*.12})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}const d=Math.hypot(a.x-mx,a.y-my);ctx.fillStyle=d<140?'rgba(103,232,249,.7)':'rgba(94,234,212,.28)';ctx.beginPath();ctx.arc(a.x,a.y,a.r+(d<140?1:0),0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}draw();
// add digital twin to index
if(location.pathname.endsWith('/')||location.pathname.endsWith('index.html')){const anchor=$('#projetos');if(anchor&&!$('#alan-os-map')){const sec=document.createElement('section');sec.id='alan-os-map';sec.className='section';sec.innerHTML='<div class="section-top reveal"><span>05</span><p>ALAN.OS / DIGITAL TWIN</p></div><div class="section-narrow"><h2 style="text-align:center">Seu ecossistema como <em>um sistema.</em></h2><p style="text-align:center;color:rgba(255,255,255,.5);max-width:720px;margin:0 auto 30px">Explore os módulos. Abra o terminal. Pergunte ao núcleo. A interface é uma representação experimental do modo como Alan conecta competências, projetos e direção técnica.</p></div><div class="os-mini-metrics"><div class="os-mini-metric"><small>COGNITIVE CORE</small><strong>AEON</strong><em> / ACTIVE</em></div><div class="os-mini-metric"><small>ROBOTICS</small><strong>READY</strong><em> / LAB</em></div><div class="os-mini-metric"><small>DATA</small><strong>ALPHA</strong><em> / FLOW</em></div><div class="os-mini-metric"><small>FIELD</small><strong>RESEARCH</strong><em> / TARGET</em></div></div><div class="os-module-map"><div class="os-lines"><svg viewBox="0 0 1200 620" preserveAspectRatio="none"><line x1="600" y1="310" x2="210" y2="150"/><line x1="600" y1="310" x2="990" y2="150"/><line x1="600" y1="310" x2="210" y2="470"/><line x1="600" y1="310" x2="990" y2="470"/><line x1="600" y1="310" x2="600" y2="95"/><line x1="600" y1="310" x2="600" y2="525"/></svg></div><div class="os-core"><div>ALAN.OS<small>CORE ONLINE</small></div></div><div class="os-node os-n1" data-open="aeon"><b>AEON</b><span>COGNITIVE ENGINE</span></div><div class="os-node os-n2" data-open="robotics"><b>ROBOTICS</b><span>PHYSICAL SYSTEMS</span></div><div class="os-node os-n3" data-open="alpha"><b>ALPHA</b><span>DATA LAB</span></div><div class="os-node os-n4" data-open="system"><b>FIELD SYSTEMS</b><span>REMOTE RESEARCH</span></div><div class="os-node os-n5" data-open="about"><b>SKILLS</b><span>TRANSFERABLE STACK</span></div><div class="os-node os-n6" data-open="system"><b>MISSION CONTROL</b><span>COMMAND CENTER</span></div></div>' ;anchor.parentNode.insertBefore(sec,anchor);$$('.os-node',sec).forEach(n=>n.onclick=()=>openConsole(n.dataset.open));}}
})();
