const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);

const dot=$('.cursor-dot'),ring=$('.cursor-ring');
window.addEventListener('pointermove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.style.left=e.clientX+'px';ring.style.top=e.clientY+'px'});
$$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{ring.style.width='52px';ring.style.height='52px'});el.addEventListener('mouseleave',()=>{ring.style.width='34px';ring.style.height='34px'})});

window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('.progress').style.width=(scrollY/h*100)+'%'});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
$$('.reveal').forEach(e=>observer.observe(e));

const menuBtn=$('#menuBtn'),nav=$('.nav');
menuBtn.addEventListener('click',()=>{nav.classList.toggle('open');menuBtn.textContent=nav.classList.contains('open')?'×':'☰'});
$$('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));

const modal=$('#modal');
const data={
 aeon:{type:'AI / COGNITIVE SYSTEMS',title:'AEON',text:'Laboratório pessoal de arquitetura para agentes inteligentes, reunindo memória, knowledge graph, RAG, validação e orquestração. A proposta é investigar como modelos podem deixar de ser apenas uma interface e passar a operar como sistemas.',tags:['AI AGENTS','RAG','LLM','KNOWLEDGE GRAPH']},
 include:{type:'EDTECH / HARDWARE',title:'INCLUDE',text:'Projeto de educação tecnológica em que robótica e automação são usadas para desenvolver raciocínio, criatividade e resolução de problemas. Uma experiência de ensino conectada a prototipagem prática.',tags:['ROBOTICS','AUTOMATION','EDTECH']},
 alpha:{type:'DATA / MACHINE LEARNING',title:'ALPHA APP',text:'Ambiente experimental de previsão e avaliação de modelos, com backtesting, calibração, engines híbridas e experimentação de aprendizado de máquina. O foco é medir, testar e iterar.',tags:['JAVASCRIPT','ML','BACKTEST','CALIBRATION']}
};
$$('.build-card').forEach(card=>card.addEventListener('click',()=>{window.location.href='projects/'+card.dataset.modal+'.html';return;
 const d=data[card.dataset.modal];$('#modalType').textContent=d.type;$('#modalTitle').textContent=d.title;$('#modalText').textContent=d.text;$('#modalTags').innerHTML=d.tags.map(t=>`<span>${t}</span>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');
}));
$('#closeModal').onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
modal.addEventListener('click',e=>{if(e.target===modal)$('#closeModal').click()});

const panel=$('#commandPanel');
function openCommands(){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}
function closeCommands(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
$('#commandBtn').onclick=openCommands;$('#closeCommand').onclick=closeCommands;
$$('.command-box [data-go]').forEach(b=>b.onclick=()=>{closeCommands();document.querySelector(b.dataset.go).scrollIntoView({behavior:'smooth'})});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}if(e.key==='Escape'){closeCommands();modal.classList.remove('open')}});

const sections=[...$$('main section[id]')],links=[...$$('.nav a')];
const active=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-40% 0px -50% 0px'});
sections.forEach(s=>active.observe(s));

const gameCanvas=$('#cometCanvas');
if(gameCanvas){
 const gameContext=gameCanvas.getContext('2d'),gameStage=gameCanvas.parentElement,gameMessage=$('#gameMessage'),startGame=$('#startGame'),gameStatus=$('#gameStatus'),scoreOutput=$('#gameScore'),waveOutput=$('#gameWave'),bestOutput=$('#gameBest'),lifeOutput=[...document.querySelectorAll('.game-lives span')];
 let gameWidth=0,gameHeight=0,animationFrame=0,lastFrame=0,spawnTimer=0,score=0,wave=1,lives=3,playing=false,playerX=0,stars=[],comets=[],shots=[],sparks=[];
 const savedBest=Number(localStorage.getItem('cometRunBest')||0);bestOutput.textContent=String(savedBest).padStart(6,'0');
 const random=(min,max)=>Math.random()*(max-min)+min;
 function resizeGame(){const ratio=Math.min(window.devicePixelRatio||1,2),bounds=gameStage.getBoundingClientRect();gameWidth=bounds.width;gameHeight=Math.max(390,Math.min(620,gameWidth*.58));gameCanvas.style.height=gameHeight+'px';gameCanvas.width=gameWidth*ratio;gameCanvas.height=gameHeight*ratio;gameContext.setTransform(ratio,0,0,ratio,0,0);playerX=playerX||gameWidth/2;stars=Array.from({length:Math.ceil(gameWidth/11)},()=>({x:random(0,gameWidth),y:random(0,gameHeight),size:random(.4,1.8),speed:random(8,25)}))}
 function updateHud(){scoreOutput.textContent=String(score).padStart(6,'0');waveOutput.textContent=String(wave).padStart(2,'0');lifeOutput.forEach((life,index)=>life.classList.toggle('lost',index>=lives))}
 function resetGame(){score=0;wave=1;lives=3;playerX=gameWidth/2;spawnTimer=0;comets=[];shots=[];sparks=[];updateHud()}
 function setPlayerPosition(event){const bounds=gameCanvas.getBoundingClientRect(),source=event.touches?event.touches[0]:event;playerX=Math.max(26,Math.min(gameWidth-26,(source.clientX-bounds.left)/bounds.width*gameWidth))}
 function fire(){if(!playing)return;shots.push({x:playerX,y:gameHeight-46,speed:620});for(let i=0;i<3;i++)sparks.push({x:playerX+random(-5,5),y:gameHeight-42,vx:random(-25,25),vy:random(15,65),life:.35})}
 function spawnComet(){const radius=random(18,36)+wave*.8,vertices=Array.from({length:random(7,10)},()=>random(.72,1.12));comets.push({x:random(radius,gameWidth-radius),y:-radius,radius,speed:random(65,105)+wave*12,rotation:random(0,7),spin:random(-2,2),vertices,hue:Math.random()>.72?'#9eb7ad':'#788f82'})}
 function explode(comet){for(let i=0;i<12;i++)sparks.push({x:comet.x,y:comet.y,vx:random(-100,100),vy:random(-100,100),life:random(.25,.6),color:comet.hue})}
 function endGame(){playing=false;cancelAnimationFrame(animationFrame);const best=Math.max(score,Number(localStorage.getItem('cometRunBest')||0));localStorage.setItem('cometRunBest',best);bestOutput.textContent=String(best).padStart(6,'0');gameStatus.textContent='STATUS: SIGNAL LOST';gameMessage.classList.add('visible');gameMessage.querySelector('h3').textContent='O núcleo perdeu o sinal.';gameMessage.querySelector('p').textContent=`Pontuação final: ${score}. Respire, ajuste a mira e tente novamente.`;startGame.textContent='TENTAR NOVAMENTE ↗'}
 function drawShip(){gameContext.save();gameContext.translate(playerX,gameHeight-30);gameContext.shadowBlur=24;gameContext.shadowColor='#ff9b43';gameContext.fillStyle='#ffb45b';gameContext.beginPath();gameContext.moveTo(0,-19);gameContext.lineTo(15,14);gameContext.lineTo(0,9);gameContext.lineTo(-15,14);gameContext.closePath();gameContext.fill();gameContext.fillStyle='#fff5d6';gameContext.beginPath();gameContext.arc(0,-5,4,0,Math.PI*2);gameContext.fill();gameContext.restore()}
 function drawCore(){const x=gameWidth/2,y=gameHeight-30,r=Math.min(42,gameWidth*.07);gameContext.save();gameContext.translate(x,y);gameContext.shadowBlur=32;gameContext.shadowColor='#ff8a3d';gameContext.strokeStyle='#ffb45b';gameContext.lineWidth=3;gameContext.beginPath();gameContext.arc(0,0,r,0,Math.PI*2);gameContext.stroke();gameContext.strokeStyle='#37e8ff';gameContext.lineWidth=2;gameContext.setLineDash([8,5]);gameContext.beginPath();gameContext.arc(0,0,r+9,-.8,2.4);gameContext.stroke();gameContext.setLineDash([]);gameContext.fillStyle='#fff0c2';gameContext.shadowBlur=22;gameContext.beginPath();gameContext.arc(0,0,8,0,Math.PI*2);gameContext.fill();gameContext.restore()}
 function drawAsteroid(comet){gameContext.save();gameContext.translate(comet.x,comet.y);gameContext.rotate(comet.rotation);gameContext.shadowBlur=14;gameContext.shadowColor='#162b2c';gameContext.fillStyle=comet.hue;gameContext.strokeStyle='#bfd6c2';gameContext.lineWidth=1.2;gameContext.beginPath();comet.vertices.forEach((scale,index)=>{const angle=-Math.PI/2+index*Math.PI*2/comet.vertices.length,px=Math.cos(angle)*comet.radius*scale,py=Math.sin(angle)*comet.radius*scale;if(index===0)gameContext.moveTo(px,py);else gameContext.lineTo(px,py)});gameContext.closePath();gameContext.fill();gameContext.stroke();gameContext.fillStyle='rgba(16,31,30,.55)';for(let index=0;index<Math.min(4,comet.vertices.length);index++){const angle=index*1.8+.8,crater=comet.radius*random(.08,.18);gameContext.beginPath();gameContext.arc(Math.cos(angle)*comet.radius*.42,Math.sin(angle)*comet.radius*.42,crater,0,Math.PI*2);gameContext.fill()}gameContext.restore()}
 function drawNebula(){const gradient=gameContext.createRadialGradient(gameWidth*.72,gameHeight*.42,10,gameWidth*.72,gameHeight*.42,gameWidth*.7);gradient.addColorStop(0,'rgba(39,196,205,.24)');gradient.addColorStop(.35,'rgba(16,89,163,.18)');gradient.addColorStop(1,'rgba(2,10,24,0)');gameContext.fillStyle=gradient;gameContext.fillRect(0,0,gameWidth,gameHeight);const warm=gameContext.createRadialGradient(gameWidth*.5,gameHeight*.68,0,gameWidth*.5,gameHeight*.68,gameWidth*.32);warm.addColorStop(0,'rgba(255,120,44,.16)');warm.addColorStop(1,'rgba(255,120,44,0)');gameContext.fillStyle=warm;gameContext.fillRect(0,0,gameWidth,gameHeight)}
 function draw(){gameContext.clearRect(0,0,gameWidth,gameHeight);gameContext.fillStyle='#010711';gameContext.fillRect(0,0,gameWidth,gameHeight);drawNebula();stars.forEach(star=>{gameContext.fillStyle=`rgba(170,231,255,${.28+star.size/3})`;gameContext.shadowBlur=star.size>1.3?8:0;gameContext.shadowColor='#6deaff';gameContext.fillRect(star.x,star.y,star.size,star.size)});gameContext.shadowBlur=0;gameContext.strokeStyle='rgba(55,225,255,.14)';gameContext.beginPath();gameContext.moveTo(0,gameHeight-72);gameContext.lineTo(gameWidth,gameHeight-72);gameContext.stroke();shots.forEach(shot=>{const beam=gameContext.createLinearGradient(0,shot.y,0,shot.y+24);beam.addColorStop(0,'#fff9d5');beam.addColorStop(.35,'#ffcc67');beam.addColorStop(1,'rgba(255,113,34,0)');gameContext.strokeStyle=beam;gameContext.shadowBlur=18;gameContext.shadowColor='#ff7b32';gameContext.lineWidth=4;gameContext.beginPath();gameContext.moveTo(shot.x,shot.y);gameContext.lineTo(shot.x,shot.y+24);gameContext.stroke();gameContext.shadowBlur=0});comets.forEach(drawAsteroid);drawCore();sparks.forEach(spark=>{gameContext.fillStyle=spark.color||'#ffad5c';gameContext.globalAlpha=Math.max(0,spark.life*2);gameContext.shadowBlur=10;gameContext.shadowColor=gameContext.fillStyle;gameContext.fillRect(spark.x,spark.y,3,3);gameContext.globalAlpha=1;gameContext.shadowBlur=0});drawShip()}
 function frame(time){if(!playing)return;const delta=Math.min((time-lastFrame)/1000,.035);lastFrame=time;spawnTimer+=delta;const spawnRate=Math.max(.22,.88-wave*.045);if(spawnTimer>spawnRate){spawnTimer=0;spawnComet();if(Math.random()<Math.min(.35,wave*.02))spawnComet()}stars.forEach(star=>{star.y+=star.speed*delta;if(star.y>gameHeight)star.y=0});shots.forEach(shot=>shot.y-=shot.speed*delta);comets.forEach(comet=>{comet.y+=comet.speed*delta;comet.rotation+=comet.spin*delta});sparks.forEach(spark=>{spark.x+=spark.vx*delta;spark.y+=spark.vy*delta;spark.life-=delta});comets=comets.filter(comet=>{if(comet.y-comet.radius>gameHeight){lives--;updateHud();if(lives<=0)endGame();return false}return true});shots=shots.filter(shot=>shot.y>-20);sparks=sparks.filter(spark=>spark.life>0);for(let shotIndex=shots.length-1;shotIndex>=0;shotIndex--){for(let cometIndex=comets.length-1;cometIndex>=0;cometIndex--){const shot=shots[shotIndex],comet=comets[cometIndex];if(Math.hypot(shot.x-comet.x,shot.y-comet.y)<comet.radius+7){explode(comet);comets.splice(cometIndex,1);shots.splice(shotIndex,1);score+=10+wave*2;wave=1+Math.floor(score/160);updateHud();break}}}draw();animationFrame=requestAnimationFrame(frame)}
 function start(){resizeGame();resetGame();playing=true;gameMessage.classList.remove('visible');gameStatus.textContent='STATUS: ACTIVE';lastFrame=performance.now();animationFrame=requestAnimationFrame(frame)}
 startGame.addEventListener('click',start);gameCanvas.addEventListener('pointermove',setPlayerPosition);gameCanvas.addEventListener('pointerdown',event=>{setPlayerPosition(event);fire()});window.addEventListener('keydown',event=>{if(event.key===' '){event.preventDefault();fire()}if(event.key.toLowerCase()==='a'||event.key==='ArrowLeft')playerX=Math.max(26,playerX-28);if(event.key.toLowerCase()==='d'||event.key==='ArrowRight')playerX=Math.min(gameWidth-26,playerX+28)});window.addEventListener('resize',resizeGame);resizeGame();draw();
}
